### ISSUE TITLE
Consider dropping p-reflect dependency

### ISSUE THREAD

**Issue by aldenquimby** [Kikobeats/reachable-url#60]
I am using `metascraper-logo-favicon` for the first time, and noticed my project now depends on `p-reflect`

It looks to me like this dependency is not needed if you required Node 12+ instead of Node 8+ (v8 has been EOL for almost 5 years), because `Promise.allSettled` becomes available

Before:
```js
  const { isFulfilled, value, reason: error } = await pReflect(req)

  const mergedResponse = mergeResponse(isFulfilled ? value : error.response, response)
```

After:
```js
  const [{ status, value, reason: error }] = await Promise.allSettled([req])

  const mergedResponse = mergeResponse(status === 'fulfilled' ? value : error.response, response)
```

**Comment by Kikobeats** [comment]
Hello, thanks for the feedback!

I tend to use `p-reflect` in my projects: The fact `Promise.allSettled` has to received an array is very annoying, that why I prefer to use a npm package. At the end it's a very tiny package, just 300 bytes.
